# Generated by Django 4.1.5 on 2023-01-19 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='файл')),
            ],
            options={
                'verbose_name': 'файл',
                'verbose_name_plural': 'файлы',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='название')),
                ('description', models.TextField(blank=True, max_length=2000, verbose_name='описание')),
                ('deadline', models.DateTimeField(verbose_name='крайний срок')),
                ('status', models.CharField(blank=True, choices=[('CREATED', 'Поручено'), ('PROGRESS', 'В работе'), ('VERIFICATION', 'На подтверждении'), ('DONE', 'Выполнено'), ("<class 'tasks.models.status.Status.Meta'>", 'Meta')], default='CREATED', max_length=41, verbose_name='статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='изменено')),
                ('executor', models.ManyToManyField(related_name='executor_tasks', to=settings.AUTH_USER_MODEL, verbose_name='исполнители')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
            },
        ),
        migrations.CreateModel(
            name='TaskFileRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.file', verbose_name='файл')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='задача')),
            ],
            options={
                'verbose_name': 'файлы и задачи',
                'verbose_name_plural': 'файлы и задачи',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='file',
            field=models.ManyToManyField(blank=True, default=None, related_name='file_tasks', through='tasks.TaskFileRelation', to='tasks.file', verbose_name='файлы'),
        ),
        migrations.AddField(
            model_name='task',
            name='guarantor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
